### ISSUE TITLE
Font-family

### ISSUE THREAD

**Issue by martoio** [gretad711/prj-rev-bwfs-dasmoto#4]
Font family rules are inherited, so you can get away with just applying the rule to your `html` or `body` element instead of defining it for each element:
```css
body{
    font-family: 'Helvetica', sans-serif;
}
```
https://github.com/gretad711/prj-rev-bwfs-dasmoto/blob/3bb82abcfdc9fe31cbaabb4cbf88ea4d8157a20b/Dasmoto/Dasstyle.css#L46
